name: deploy Django application

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to DigitalOcean Container Registry
      run: |
        echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login -u "docr" --password-stdin registry.digitalocean.com

    - name: Build Docker Image
      run: |
        docker build -t registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/home-installer:latest .

    - name: Push Docker Image to DigitalOcean Container Registry
      run: |
        docker push registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/home-installer:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_PRIVATE_KEY }}

    - name: Deploy Docker Image to DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_SSH_USER }}@${{ secrets.DIGITALOCEAN_SERVER_IP }} << 'EOF'
          # Log in to DigitalOcean Container Registry on the Droplet
          echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login -u "docr" --password-stdin registry.digitalocean.com

          # Pull the latest Docker image from DigitalOcean Container Registry
          docker pull registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/home-installer:latest

          # Stop and remove the existing container
          docker stop django-app || true
          docker rm django-app || true

          # Run the Docker container with the pulled image
          docker run -d --env-file ./.cred/.env --name django-app -p 8000:8000 registry.digitalocean.com/${{ secrets.DIGITALOCEAN_REGISTRY_NAME }}/home-installer:latest
        EOF
